### ISSUE TITLE
Cannot install on linux

### ISSUE THREAD

**Issue by wulabupenn** [farrellja/URD#1]
I can install the package in windows. However I had a hard time to install it on Linux. I am wondering whether the package is compatible with Linux? Thanks!

**Comment by farrellja** [comment]
It should work on Linux, but has not been extensively tested. Are you trying to install it on a Linux desktop environment through RStudio, or on a compute cluster? (I've installed and used it on a compute cluster successfully, but have not tested it through RStudio.) Can you tell me more about what went wrong?

**Comment by wulabupenn** [comment]
Thank you. I self-solved the problem. It was the problem with installing udunist2 not the URD.
