### ISSUE TITLE
Importing Seurat ro URD

### ISSUE THREAD

**Issue by fereshtehizadi** [farrellja/URD#11]
Hi,

I have clustered my cells by Seurat, now I would like to trace gene expression pattern during the development by URD. I tried to figure how how I could import my Seurat object to URD but unfortunately I failed. Could you please help me in this regard?

Thanks lot in advance

**Comment by farrellja** [comment]
Hi. You probably want to try the function ```seuratToURD```. You can get more information about the function by typing ```?seuratToURD```. If you had a problem recently with this function, you may try reinstalling from the debug branch, as I recently updated this function to correct a bug where it would not important properly if PCA or tSNE had not been calculated in Seurat. 

If you missed them, you will likely find the two guides in ```URD/Analyses``` in this repository useful as you try to apply the software, as well as the internal documentation. You can type ```?URD``` to get a starter set of links, and the index is at the bottom that links to the documentation for all functions.

**Comment by fereshtehizadi** [comment]
Sorry but whatever I am doing, find variable gene function returns error



```
> var.by.stage <- lapply(seq(3,12,3), function(n) {
+   findVariableGenes(axial, cells.fit=cellsInCluster(axial, "STAGE", stages[(n-2):n]), set.object.var.genes=F, diffCV.cutoff=0.3, mean.min=.005, mean.max=100, main.use=paste0("Stages ", stages[n-2], " to ", stages[n]), do.plot=T)
+ })
 Show Traceback
 
 Rerun with Debug
 Error in fitdistr(size_factor, "Gamma") : 
  'x' must be a non-empty numeric vector > axial@meta
       nGene    nUMI    orig.ident   CELL STAGE GENO BATCH stage.nice
s1.1    4331  373762 SeuratProject   s1.1   h16   WT     1        h16
s1.2    5603 1074639 SeuratProject   s1.2   h16   WT     1        h16
s1.3    2064   49544 SeuratProject   s1.3   h16   WT     1        h16
s1.4    4680  772399 SeuratProject   s1.4   h16   WT     1        h16
s1.5    3876  272356 SeuratProject   s1.5   h16   WT     1        h16
s1.6    2557  122314 SeuratProject   s1.6   h16   WT     1        h16
s1.7    4368  644005 SeuratProject   s1.7   h16   WT     1        h16
```
