### ISSUE TITLE
Supplementary Analysis

### ISSUE THREAD

**Issue by Kgies10** [farrellja/URD#2]
Where I can find the supplementary analysis referenced in the quick start?  I'm having trouble finding it. Thanks!

**Comment by farrellja** [comment]
Hi,
It's supposed to be part of the supplementary materials of our paper, but did not get correctly posted. While the editors sort that out, I've added it to the repository in Analyses/SupplementaryAnalysis.

**Comment by Kgies10** [comment]
Great, thanks!
