### ISSUE TITLE
Error in simulateRandomWalksFromTips step

### ISSUE THREAD

**Issue by ksr2018** [farrellja/URD#27]
Hi all, 
I have just started to use URD. I have an object with roughly 12000 cells from 3 timepoints during differentiation. I'm currently stuck at simulateRandomWalksFromTips. I get the following error:

Error in sample.int(length(x), size, replace, prob) : too few positive probabilities

I have tried changing n.per.tip, root.visits and max.steps without any luck. I'm also not sure what these parameters are exactly, still exploring and learning. 

It would be great if anyone has ideas about how to fix this error. 
Thanks.

**Comment by farrellja** [comment]
Hi ksr2018,

Are you still having this problem? It suggests that the random walks are trying to move from a cell that has no connections to any other cell -- this probably reflects a bad diffusion map, or that the cell should have been filtered out previously. Still, it could be good to have a reproducible example to try to track this bug down. Do you have one?

Jeff

**Comment by ksr2018** [comment]
@farrellja I had this issue when I was running URD for the first time on a test dataset that I analyzed using Seurat CCA.
I re-ran the same dataset recently and have not been able to reproduce the error with this dataset. So I don't have an example for you. Sorry!
