### ISSUE TITLE
Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105

### ISSUE THREAD

**Issue by ksr2018** [farrellja/URD#28]
Hi @farrellja ,
I'm trying URD on a dataset with about 50k cells and when I try to run:

`myURDobject.biased.tm <- as.matrix(pseudotimeWeightTransitionMatrix(myURDobject, "pseudotime", logistic.params=myURDobject.ptlogistic))`

it gives the following error:

Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105

I realize this may be related to issue #6, but I do not know how to fix it. Can you please help?

Thank you.

**Comment by farrellja** [comment]
Hi @ksr2018,

I have updated the `pseudotimeWeightTransitionMatrix` function, which was having an error above 46k cells. To avoid it, it divides the data into pieces, processes them separately, and then reassembles it. Try installing from the debug branch (`devtools::install_github(repo="farrellja/URD@debug")`, should be version 1.0.3.9002) and try again. You probably will also want to remove the `as.matrix()` in the above call to keep the output as a sparseMatrix.
