### ISSUE TITLE
how to extract the Embeddings information after treeForceDirectedLayout processing

### ISSUE THREAD

**Issue by pangxueyu233** [farrellja/URD#51]
Hello,
it's really a impressive working to generate the URD algorithm. And the treeForceDirectedLayout is a important formula to visualize the single cell connection. However, recently I tried to extract the Embeddings information from URD object after treeForceDirectedLayout processing, I didn't know where that information stored. Could you help me work it out? 
Thanks

**Comment by farrellja** [comment]
@pangxueyu233 

The force-directed layout embedding is stored in the object as `object@tree$walks.force.layout`. The columns `x`, `y`, and `telescope.pt` (z) are what you want.

Best,
Jeff

**Comment by pangxueyu233** [comment]
Thanks! But I have another  problem:
How could we export a png or a svg file of plotTreeForce results ?

**Comment by farrellja** [comment]
`plotTreeForce` renders using the R package `rgl`. You can functions from that package to save resulting images (i.e. `rgl::rgl.snapshot` or `rgl::postscript`), as is written in the documentation for the function (see `?plotTreeForce`).
