### ISSUE TITLE
Weird behavior from buildTree

### ISSUE THREAD

**Issue by Olimon660** [farrellja/URD#52]
Hi @farrellja , I have been using URD for a while but recently I'm having trouble with the buildTree function. It seems no matter if I take a previous processed axial.rds object, or start from the beginning, the tree layout looks like just a mess. More specifically, even if I take a previous axial.rds after processRandomWalksFromTips, then call buildTree exactly the same as before (I kept all my code), I still get a messed tree.

I noticed that now I get some warnings from ggplot such as:
**Removed 760 rows containing missing values (geom_point).
Removed 8 rows containing missing values (geom_segment).**

If I directly load a previous axial.tree.rds, then plotTree is still able to get the expected tree layout.
I have also tried to uninstall and reinstall the package, but the problem still exists.
I suspect it could be due to some dependant that got updated but completely have no better idea.

It would be great if you can shed some light on this! I have also attached the two layouts that are supposed to be the same.
Thanks!

![image](https://user-images.githubusercontent.com/21287206/68649306-7971c380-0576-11ea-9d88-01f6ec392c55.png)
![image](https://user-images.githubusercontent.com/21287206/68649350-9908ec00-0576-11ea-97c7-dc9291beec6a.png)

**Comment by farrellja** [comment]
Hi @Olimon660 ,

I think this is related to the **ggraph** package -- there seems to be a major change in behavior of one of the dendrogram functions I used from it between versions 1 and 2. See the discussion in Issue #45 and let me know if that helps you. If not, we can revisit :)

**Comment by Olimon660** [comment]
> Hi @Olimon660 ,
> 
> I think this is related to the **ggraph** package -- there seems to be a major change in behavior of one of the dendrogram functions I used from it between versions 1 and 2. See the discussion in Issue #45 and let me know if that helps you. If not, we can revisit :)

solved it like magic... massive thanks!!
