### ISSUE TITLE
the GENE name of GSE106474_UMICounts.txt.gz is human's

### ISSUE THREAD

**Issue by kzxkzx** [farrellja/URD#58]
sorry to bother you, I want to go through your perfect work URD, by following your supply guide, I found the GENE name of GSE106474_UMICounts.txt.gz is human's, not zebrfish, making me some comfusing.I need to continue or change those gene to corresponding zebrafish genes? Thank you

**Comment by farrellja** [comment]
The genes are zebrafish genes, they're just in all caps. Whenever possible, they are the ZFIN gene name.
