### ISSUE TITLE
Possibly constrained R version?

### ISSUE THREAD

**Issue by snugghash** [farrellja/URD#9]
I've noticed that a lot of dependencies (and consequently the install) break with R version 3.5.1. I can confirm that it did not have the same errors when installing under R-3.4.3 and R-3.4.1. 

Perhaps this should be mentioned somewhere so others don't waste their time. I can open a PR to edit the install.md if this is confirmed.

**Comment by farrellja** [comment]
Interesting -- I have not tried installing under R 3.5 or 3.5.1

I think all dependencies are actively maintained, so I expect this should iron itself out soon.

I added a note to install.md to warn people for now.
